name = "2023-fall-game-jam"
default_targets = ["macos", "appimage", "win64", "lovejs"]
build_directory = "makelove-build"

love_files = [
    "::git-ls-tree::",

    "-*/.*",
    "-*/dist*",
]

[lovejs]
title = "2023 Fall Game Jam Game by Mike Purdy"
memory = "200000000"  # starting memory of the webpage (default is 20 MB)

[macos]
# optionally, you can include a mac-specific icon, if not mac will use the same icon as other targets
#icon_file = "macIcon.png"  # or macIcon.icns

[macos.app_metadata]
CFBundleName = "2023 Fall Game Jam"
CFBundleIdentifier = "dev.mikepurdy.2023fallgamejam"
NSHumanReadableCopyright = "Copyright © 2023 Mike Purdy"
CFBundleShortVersionString = "0.0.1"

[windows.exe_metadata]
FileDescription = "{name} - {version}" # "LÖVE {löve version}"
FileVersion = "{version}" # "{löve version}"
CompanyName = "Mike Purdy" # "LÖVE World Domination Inc."
LegalCopyright = "Copyright © 2023 Mike Purdy"
ProductName = "{name}" # "LÖVE"
ProductVersion = "<same as FileVersion>"
OriginalFilename = "purdy-fall-2023.exe" # "love.exe"
